sonar.projectKey=pi-frontend
sonar.projectName=PI Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=TON_TOKEN