pipeline {
    agent any

    tools {
        nodejs 'NodeJS 22'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'd49ea3fa-057f-48a2-a3cd-b9a78f6bca26',
                    url: 'https://github.com/ademmBA/oralis-ai.git'
            }
        }

        stage('Install') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t pi-backend ./backend'
            }
        }

        stage('Docker Run') {
            steps {
                sh 'docker run -d -p 3000:3000 pi-backend'
            }
        }
    }
}