pipeline {
    agent any

    tools {
        nodejs 'NodeJS 20'
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/ademmBA/oralis-ai.git'
            }
        }

        stage('Install') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    sh 'npm run test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t pi-backend ./backend'
            }
        }

        stage('Docker Run') {
            steps {
                sh 'docker run -d -p 3000:3000 pi-backend'
            }
        }
    }
}