export const DEFAULT_SETTINGS = {
  profiles: {
    seizureSafe: false,
    visionImpaired: false,
    adhdFriendly: false,
    cognitiveDisability: false,
    keyboardNavigation: false,
    blindUsers: false,
  },
  content: {
    fontSizing: 0,
    lineHeight: 0,
    letterSpacing: 0,
    readableFont: false,
    highlightTitles: false,
    highlightLinks: false,
    textAlign: "default",
  },
  colors: {
    darkContrast: false,
    lightContrast: false,
    highContrast: false,
    highSaturation: false,
    lowSaturation: false,
    monochrome: false,
    textColor: null,
    titleColor: null,
    backgroundColor: null,
  },
  orientation: {
    muteSounds: false,
    hideImages: false,
    readMode: false,
    readingGuide: false,
    stopAnimations: false,
    readingMask: false,
    highlightHover: false,
  },
};